[[https://git.sr.ht/~codegouvfr/codegouvfr-sources/tree/master/item/LICENSE.md][https://img.shields.io/badge/Licence%20Ouverte-orange.svg?style=flat-square]]

* Liste des comptes d'organisation

Cette page présente les listes des comptes d'organisation où les
administrations publiques publient des codes sources.

Ces informations sont les sources du site [[https://code.gouv.fr][code.gouv.fr]].

- [[https://git.sr.ht/~codegouvfr/codegouvfr-sources/blob/master/comptes-organismes-publics.yml][comptes-organismes-publics.yml]] : Liste principale.                                
- [[https://git.sr.ht/~codegouvfr/codegouvfr-sources/blob/master/comptes-organismes-publics-autres-forges][comptes-organismes-publics-autres-forges]] : Forges non suivies sur [[https://code.gouv.fr][code.gouv.fr]].

* Contribuer

Vos contributions sont les bienvenues !

Pour chaque compte d'organisation, vous pouvez indiquer :

- =service_of= : L'institution dont dépend le compte.  S'il y en a
  plusieurs, placer la plus proche en premier.
- =floss_policy= : Le lien vers la politique logiciels libres du compte.

Vous pouvez envoyer vos correctifs ("patches") par mail en texte brut
sur la liste de développement : [[mailto:~codegouvfr/dev@lists.sr.ht][~codegouvfr/dev@lists.sr.ht]]

Pour ces mails, pensez à configurer votre copie locale du dépôt :

: git config format.subjectPrefix 'PATCH codegouvfr-sources'

Vous pouvez signaler un nouveau compte d'organisation ou une nouvelle
forge en écrivant à [[mailto:contact@code.gouv.fr][contact@code.gouv.fr]].

Nous n'acceptons les contributions que si elles sont signées (/signed
off/) du vrai nom du contributeur.  En signant ses contributions, le
contributeur accepte le [[https://developercertificate.org][developer certificate of origin]].

* Licence

Le contenu de ce dépôt est sous [[file:LICENSE.md][licence Ouverte 2.0]].

2018-2023 DINUM, Etalab.
